# Generated by Django 4.1.3 on 2022-11-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_costumer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumer',
            name='id',
        ),
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
