# Generated by Django 4.1.3 on 2022-11-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_costumer_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='costumer',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.CharField(max_length=20),
        ),
    ]
