# Generated by Django 4.1.3 on 2022-11-13 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_order_costumer_alter_order_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='costumer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.costumer'),
        ),
    ]
